// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Query struct {
}

type Reader struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
